// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package web

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"context"
	"html/template"
	"log"
	"net/http"
)

type Reaction struct {
	url      string
	callback func(w http.ResponseWriter, r *http.Request)
}

func Init() {
	fs := http.FileServer(http.Dir("static/"))
	http.Handle("/static/", http.StripPrefix("/static/", fs))

	home := Home()
	homeHTML, err := templ.ToGoHTML(context.Background(), home)
	if err != nil {
		log.Fatalf("failed to convert to html: %v", err)
	}

	index := template.Must(template.ParseFiles("index.html"))

	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		index.Execute(w, homeHTML)
	})

	http.ListenAndServe(":8080", nil)
}

var _ = templruntime.GeneratedTemplate
